"""
trodes_io.py

A thin layer over ``trodesnetwork`` so the rest of the package never touches the
socket API directly. Everything that subscribes to a Trodes channel goes through
here, which keeps the connection details (channel names, server address, message
shape) in one place.
"""

import time

from trodesnetwork.socket import SourceSubscriber

DEFAULT_SERVER = "tcp://127.0.0.1:49152"


# ----------------------------------------------------------------------------
# Subscribing to channels
# ----------------------------------------------------------------------------

def subscribe(channel, server=DEFAULT_SERVER):
    """Return a SourceSubscriber for ``channel`` on the given Trodes server."""
    return SourceSubscriber(channel, server_address=server)


def iter_messages(channel, server=DEFAULT_SERVER):
    """Yield messages from a Trodes channel forever (blocks between samples)."""
    sub = subscribe(channel, server)
    while True:
        yield sub.receive()


def iter_positions(server=DEFAULT_SERVER):
    """Yield raw messages from ``source.position`` (the tracked x/y stream)."""
    return iter_messages("source.position", server)


def iter_events(server=DEFAULT_SERVER):
    """Yield raw messages from ``source.event``."""
    return iter_messages("source.event", server)


# ----------------------------------------------------------------------------
# Pulling x, y out of a Trodes position message (defensive about its shape)
# ----------------------------------------------------------------------------

def extract_xy(msg):
    """Return ``(x, y)`` floats from a position message, or ``None`` if absent."""
    if isinstance(msg, dict):
        for kx, ky in (("x", "y"), ("xloc", "yloc"), ("X", "Y")):
            if kx in msg and ky in msg:
                return float(msg[kx]), float(msg[ky])
        return None
    if isinstance(msg, (bytes, str)):
        text = msg.decode() if isinstance(msg, bytes) else msg
        if "," in text:
            try:
                x, y = text.split(",")[:2]
                return float(x), float(y)
            except ValueError:
                return None
    return None


# ----------------------------------------------------------------------------
# Timestamps
#
# Per the Trodes Networking API:
#   - source.position carries 'timestamp': "The hardware sample count since
#     streaming began". Neural/spike/LFP/event streams stamp the SAME counter as
#     'localTimestamp', so this sample count is the exact key for aligning
#     position with neural activity -- equal sample counts mean the same instant.
#   - Some streams also carry 'systemTimestamp': "The 64-bit computer timestamp
#     when the sample was first processed", an integer Unix time in NANOSECONDS.
#     The documented position message does NOT include it, but we read it if a
#     given Trodes build happens to provide it.
# ----------------------------------------------------------------------------

def extract_sample_count(msg):
    """Return the MCU hardware sample count, or ``None``.

    This counter is generated by the MCU's sample clock, and the MCU stamps the
    SAME counter onto the neural streams (where it appears as ``localTimestamp``).
    It is therefore the real key for aligning position with neural activity --
    equal sample counts mean the same instant. This, not any Unix wall-clock, is
    the time that comes from the MCU.
    """
    if isinstance(msg, dict):
        for key in ("timestamp", "localTimestamp"):
            if key in msg:
                try:
                    return int(msg[key])
                except (TypeError, ValueError):
                    pass
    return None


def extract_system_time_ns(msg):
    """Return Trodes' ``systemTimestamp`` (Unix nanoseconds), or ``None``.

    Per the docs this is "the 64-bit computer timestamp when the sample was first
    processed" -- i.e. the RECORDING COMPUTER's clock, not the MCU. It is absent
    from the documented position message (callers fall back to a receive-time
    stamp). Either way it is downstream of the MCU sample clock.
    """
    if isinstance(msg, dict):
        if "systemTimestamp" in msg:
            try:
                return int(msg["systemTimestamp"])
            except (TypeError, ValueError):
                pass
    return None


def now_unix_ns():
    """Current Unix time in nanoseconds on THIS client's clock (time.time_ns).

    The Networking API suggests this for stamping samples on the receiving
    machine. It is a client-side wall-clock, downstream of the MCU by network +
    processing latency -- NOT the MCU hardware time and NOT the neural
    systemTimestamp. For neural alignment, use the MCU sample count instead.
    """
    return time.time_ns()
